title: "Paul's Books"
description: "A collection of short novels and stories"
author: "Paul M."
remote_theme: pages-themes/cayman@v0.2.0

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - .github/
  - the_wrong_answer/book.toml
  - the_wrong_answer/SUMMARY.md
  - ashes_of_the_blockland/book.toml
  - ashes_of_the_blockland/SUMMARY.md
